task: 'if_nerf'
gpus: [3]

parent_cfg: 'configs/zju_mocap_exp/ndf_313.yaml'

human: 393

train_dataset:
    data_root: 'data/zju_mocap/CoreView_393'
    human: 'CoreView_393'
    ann_file: 'data/zju_mocap/CoreView_393/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/CoreView_393'
    human: 'CoreView_393'
    ann_file: 'data/zju_mocap/CoreView_393/annots.npy'
    split: 'test'

# data options
num_train_frame: 300
