task: 'if_nerf'
gpus: [0]

parent_cfg: 'configs/zju_mocap_exp/ndf_313.yaml'

human: 386

start_loss: 1

train_dataset:
    data_root: 'data/zju_mocap/CoreView_386'
    human: 'CoreView_386'
    ann_file: 'data/zju_mocap/CoreView_386/annots.npy'
    split: 'train'

test_dataset:
    data_root: 'data/zju_mocap/CoreView_386'
    human: 'CoreView_386'
    ann_file: 'data/zju_mocap/CoreView_386/annots.npy'
    split: 'test'

# data options
num_train_frame: 300
num_novel_pose_frame: 1000
